---
- hosts: cnhosts
  remote_user: root
  tasks:
    - name: start glusterfs
      service: name=glusterfs-server state=started
      when: ansible_hostname in start_hosts
  
  vars:
    - start_hosts:
        - cn02
        - cn03
        - cn05
        - cn06
