---
- hosts: cnhosts
  remote_user: root
  tasks:
    - name: gluster volume remove brick
      shell: yes|gluster volume remove-brick {{ volume_name }} {{ remove_hosts }} force
      when: ansible_hostname == control_host

    - name: setfattr -x 1
      shell: setfattr -x trusted.glusterfs.volume-id {{ volume_dir }}
      when: ansible_hostname in set_hosts
    - name: setfattr -x 2
      shell: setfattr -x trusted.gfid {{ volume_dir }}
      when: ansible_hostname in set_hosts

  vars:
    - control_host: cn02
    - volume_name: gv0
    - volume_dir: /export/sda6/brick
    - set_hosts:
        - cn05
        - cn06
    - remove_hosts: 
        cn05:/export/sda6/brick
        cn06:/export/sda6/brick
 
