---
- hosts: cnhosts
  remote_user: root
  tasks:
    - name: gluster peer detach
      shell: gluster peer detach {{ item }}
      with_items: detach_hosts
      when: ansible_hostname == control_host
  vars:
    - control_host: cn02
    - detach_hosts:
        - cn03
        - cn05
        - cn06

