---
- hosts: cnhosts
  remote_user: root
  tasks:
    - name: gluster volume add brick
      shell: gluster volume add-brick {{ volume_name }} {{ cn_hosts }}
      when: ansible_hostname == control_host

  vars:
    - control_host: cn02
    - volume_name: gv0
    - cn_hosts: 
        cn05:/export/sda6/brick
